### ISSUE TITLE
Not detecting the correct default browser

### ISSUE THREAD

**Issue by andreldm** [jakub-g/x-default-browser#3]
When using node-inspector's node-debug, instead of chromium, firefox gets open. Drilling through the dependencies here I am. Here's some info that might help us nail this down:

```
$ xdg-mime query default x-scheme-handler/http
chromium.desktop

$ biased-opener --verbose --browsers 'chrome' 'http://example.org'
Default browser is chromium; looking further for browsers matching [chrome]...
No browser matching [chrome] found in the system!

$ biased-opener --verbose --browsers 'chromium' 'http://example.org'
Using default browser via opener; it should open chromium

Firefox opens
```

System: Archlinux 64-bit fully updated
DE: Xfce 4.12
Default browser: Firefox
How the browser was set as default: via [Xfce Preferred Applications](http://docs.xfce.org/xfce/exo/preferred-applications) dialog

**Comment by jakub-g** [comment]
Thanks for the report! Interesting edge case. So it seems it's better in biased-opener (which is used by node-inspector's `node-debug`) to always rely on browser-launcher. I'll publish a fix soon.

**Comment by jakub-g** [comment]
Ad `x-default-browser` itself, it's in fact tricky to answer "what is the default browser" since the user can have different handlers for `HTTP://` `HTTPS://`, `.htm`, `.html` etc.

So I think I'll update the `biased-opener` to at least not open the different browser than the one detected, but I'll not change the `x-default-browser` itself and make it return the `HTTP://` handler, as it is the case right now.

**Comment by andreldm** [comment]
Thank you for looking into this. I'll test your fix as soon as you push.

**Comment by jakub-g** [comment]
I released a new version of biased-opener. When you uninstall and reinstall node-inspector, you should get a fix.

Let me know if it works for you.

**Comment by andreldm** [comment]
Working just fine:

```
    $ biased-opener --verbose --browsers 'chromium' 'http://example.org'
    Default browser is firefox; looking further for browsers matching [chromium]...
    Browser chromium started with PID: 25177
```

But node-inspector(uninstalled and installed) no longer opens a browser, not even firefox:

```
    $ node-inspector server.js
    Node Inspector v0.10.1
    Visit http://127.0.0.1:8080/debug?ws=127.0.0.1:8080&port=5858 to start debugging.
```

Actually, node-inspector doesn't start my app on locahost:3000, I guess this might be a downstream bug. I'll try again later at home. Once again, thanks.

**Comment by jakub-g** [comment]
`node-inspector` does not open a browser, you need `node-debug`

**Comment by andreldm** [comment]
Yeah, sure, I was in a hurry and forgot who is who. Now everything is working nicely.
Great work!
Cheers.

**Comment by jakub-g** [comment]
Good. Thanks for the detailed report and for verifying!
