### ISSUE TITLE
Vulnerability in the sub-dependent package

### ISSUE THREAD

**Issue by bponomarenko** [jakub-g/x-default-browser#9]
`x-default-browser` depends on `default-browser-id@^1.0.4` which has sub-dependency on `trim-newlines@1.0.0` package. `trim-newlines@1.0.0` contains **high severity** DoS vulnerability: https://snyk.io/vuln/SNYK-JS-TRIMNEWLINES-1298042
(full dependencies path is `x-default-browser@0.4.0 ‣ default-browser-id@1.0.4 ‣ meow@3.7.0 ‣ trim-newlines@1.0.0`)

Luckily `trim-newlines` package has newer version where this vulnerability was fixed, and never version of `default-browser-id` package that depends on a latest `trim-newlines`. So the fix would be just to bump `default-browser-id` dependency to the latest `3.0.0` version.

**Comment by stevensacks** [comment]
Storybook uses this as a dependency so this issue is affecting a lot of people.

**Comment by shajz** [comment]
Pinging maintainer/owner @jakub-g 
With PRs #10 and #11, this should allow packages (like storybook) that depends on `x-default-browser` to rid themselves of vulnerabilities.
see https://github.com/jakub-g/x-default-browser/pull/8#issuecomment-1204956936

Thanks!

**Comment by jakub-g** [comment]
Hey folks, sorry, I had no idea this package became a dep of storybook. I will try to issue an update in the coming days.

**Comment by lucascaton** [comment]
Thanks, @jakub-g. Any news on this? Is there anything we can do to help?

**Comment by lucascaton** [comment]
@jakub-g?

**Comment by jakub-g** [comment]
Sorry again folks, I've been off and away from my computer in thelast
weeks, I'm gonna be back on Monday and will release an update ASAP.

**Comment by shajz** [comment]
Hi @jakub-g do you need any help for the release ?

**Comment by alopix** [comment]
Any chance we can help with getting this released @jakub-g?

**Comment by jakub-g** [comment]
Sorry for extremely poor handling of this.

I just [released v0.5.0](https://www.npmjs.com/package/x-default-browser?cachebuster) to npm. Thx @alopix for the PRs!

Edit: 0.5.0 is broken on MacOS, just released 0.5.1.
